[package]
name = "libharu"
version = "0.1.0"
authors = ["Peter Reid <peter.d.reid@gmail.com>"]

[dependencies]
libc = "*"

[dependencies.libharu_sys]
git = "https://github.com/PeterReid/libharu_sys_rs"
